# Generated by Django 5.2 on 2025-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('pincode', models.IntegerField(max_length=100)),
                ('mnumber', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('aadhaar', models.IntegerField(max_length=100)),
                ('poffice', models.CharField(max_length=100)),
                ('distric', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fir',
            },
        ),
        migrations.CreateModel(
            name='Fir_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.IntegerField()),
                ('categories', models.CharField(max_length=10)),
                ('cause', models.TextField(max_length=400)),
                ('mig', models.ImageField(blank=True, db_column='Image', null=True, upload_to='staticfiles/images')),
            ],
            options={
                'db_table': 'fir_num',
            },
        ),
    ]
